name: Function Deploy

on:
  push:
    tags:
      - "*"
    paths:
      - "slate/**"
      - "main.go"
      - "template.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          key: docker-cache-{hash}
          restore-keys: |
            docker-cache-
      - uses: actions/setup-go@v2

      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Slate Doc
        run: |
          sed -i "s/VERSION/$RELEASE_VERSION/g" slate/source/index.html.md
          docker build -t slate-builder:latest slate/
          docker run --rm -v $(pwd)/static:/srv/slate/build slate-builder:latest

      - name: Build Bootstrap
        run: go build -o bootstrap

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fun-artifact
          path: |
            static/
            bootstrap

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: fun-artifact
          path: artifact

      - name: Setup Funcraft
        run: |
          sudo npm install @alicloud/fun -g
          mkdir -p ~/.fcli && echo "$FUNCRAFT_CONFIG_YML" > ~/.fcli/config.yaml
        env:
          FUNCRAFT_CONFIG_YML: ${{ secrets.FUNCRAFT_CONFIG_YML }}

      - name: Fix bootstrap permission
        run: chmod +x artifact/bootstrap

      - name: Deploy
        run: fun deploy -y
        env:
          TIMEOUT: ${{ secrets.FUNCRAFT_TIMEOUT }}
          RETRIES: ${{ secrets.FUNCRAFT_RETRIES }}
